# Generated by Django 5.1 on 2026-08-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='repository',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activity'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'Organization'},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repository'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelOptions(
            name='webhooksubscription',
            options={'verbose_name_plural': 'Webhook Subscription'},
        ),
        migrations.AddField(
            model_name='activity',
            name='source_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='source_event_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='source_provider',
            field=models.CharField(default='github', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='repository',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('repository', 'source_provider', 'source_event_id'), name='uniq_activity_source_event'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
