# Generated by Django 5.1 on 2026-08-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activity_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['repository', '-created_at'], name='idx_activity_repo_created'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['actor', '-created_at'], name='idx_activity_actor_created'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', '-created_at'], name='idx_activity_type_created'),
        ),
    ]
