# Generated by Django 5.1 on 2026-08-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activity_idx_activity_repo_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='last_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_sync_status',
            field=models.CharField(choices=[('NEVER', 'Never Synced'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='NEVER', max_length=20),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
