# Generated by Django 5.1 on 2026-08-24 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_repository_last_sync_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TrackedRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_repositories', to='core.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tracked Repositories',
                'unique_together': {('user', 'repository')},
            },
        ),
    ]
